version: '3.4'

services:

  twitterclone.api.userservice:
    image: ${DOCKER_REGISTRY-}twittercloneapiuserservice
    build:
      context: .
      dockerfile: TwitterClone.Api.UserService/Dockerfile

  twitterclone.web:
    image: ${DOCKER_REGISTRY-}twittercloneweb
    build:
      context: .
      dockerfile: TwitterClone.Web/Dockerfile